- name: shell vs command line
  hosts: localhost
  become: no 
  tasks:
  - name: command line
    ansible.builtin.commndline: "echo, 'hi from commandline' > /tmp/commandline.txt "
    
  - name: shell module
    ansible.builtin.shell: "echo ,'Hi from shell module' > /tmp/shell.txt"  