- name: backend setup
  hosts: backend
  become: yes 
  tasks:
  # dnf module disable nodejs -y
  - name: disable node js 
    ansible.builtin.command: dnf module disable nodejs -y
  #   dnf module enable nodejs:20 -y
  - name: enable node js 
    ansible.builtin.command: dnf module enable nodejs:20 -y

  #dnf install nodejs -y
  - name: install node js  
    ansible.builtin.dnf:
      name: nodejs
      state: installed  

  #useradd expense
  # ansible add user
  - name:  useradd expense #useradd expense ansible add user
    ansible.builtin.user:
      name: expemse

  # mkdir /app
  # ansible.create directry
  - name: create app direcotry
    ansible.builtin.file:
      path: /app
      state: directory

  # Download the application code to created app directory.
  # curl -o /tmp/backend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
  # download file - ansible.builtin.get_url

  - name: download backend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  # cd /app
  # unzip /tmp/backend.zip
  #ansible unzip module

  - name: unzip/archieve backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes   #already files present 

  #cd /app
  #npm install  
  #builtin command  
  #args command module to install in /app

  - name: install npm dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app







  

     

