- name: configure front end
  become: yes 
  hosts: frontend
  tasks:
  # dnf install nginx -y 
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  # systemctl enable nginx    
  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx 
      state: started
      enabled: yes 
      
  # rm -rf /usr/share/nginx/html/*
  - name: delete default webiste
  ansible.builtin.file:
    path: /usr/share/nginx/hmtl
    state: absent



      