- name: configure front end
  become: yes 
  hosts: frontend
  tasks:
  # dnf install nginx -y 
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  # systemctl enable nginx    
  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx 
      state: started
      enabled: yes

  - name: delete default website
    ansible.builtin.file:
      path: /usr/share/nginx/hmtl
      state: absent    
      
      



      