- name: configure front end
  become: yes 
  hosts: frontend
  tasks:
  # dnf install nginx -y 
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  # systemctl enable nginx    
  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx 
      state: started
      enabled: yes

  - name: delete default website
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html direcotry
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory  

  #download and unzip
  # curl -o /tmp/frontend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
  # cd /usr/share/nginx/html
  # unzip /tmp/frontend.zip

  - name: download and archive front end code
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes 

  - name: copy backend conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf    

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enable: yes    


      
      



      